---
version: '2'
services:
  elasticsearch: 
    build: es
    ports:
      - 9200:9200
    ulimits:
      notile:
         soft: 65536
         hard: 65536

  kibana:
   build: kibana
   ports:
     - 5601:5601
   depends_on:
     - es

